name: Autograding Tests
on:
  push:
    branches:
      - main
      - develop
      - 'feat/*'
  pull_request: {}
  repository_dispatch: {}
permissions:
  checks: write
  actions: read
  contents: write
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: exercice-1a
      id: exercice-1a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-1a
        setup-command: npm install
        command: npm run test exercice-1.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-1b
      id: exercice-1b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-1b
        setup-command: npm install
        command: npm run test exercice-1.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-2a
      id: exercice-2a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-2a
        setup-command: npm install
        command: npm run test exercice-2.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-2b
      id: exercice-2b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-2b
        setup-command: npm install
        command: npm run test exercice-2.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-2c
      id: exercice-2c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-2c
        setup-command: npm install
        command: npm run test exercice-2.test.js -- --subtest=c
        timeout: 10
        max-score: 1
    - name: exercice-2d
      id: exercice-2d
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-2d
        setup-command: npm install
        command: npm run test exercice-2.test.js -- --subtest=d
        timeout: 10
        max-score: 1
    - name: exercice-3a
      id: exercice-3a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-3a
        setup-command: npm install
        command: npm run test exercice-3.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-3b
      id: exercice-3b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-3b
        setup-command: npm install
        command: npm run test exercice-3.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-3c
      id: exercice-3c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-3c
        setup-command: npm install
        command: npm run test exercice-3.test.js -- --subtest=c
        timeout: 10
        max-score: 1
    - name: exercice-3d
      id: exercice-3d
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-3d
        setup-command: npm install
        command: npm run test exercice-3.test.js -- --subtest=d
        timeout: 10
        max-score: 1
    - name: exercice-3e
      id: exercice-3e
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-3e
        setup-command: npm install
        command: npm run test exercice-3.test.js -- --subtest=e
        timeout: 10
        max-score: 1
    - name: exercice-4a
      id: exercice-4a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-4a
        setup-command: npm install
        command: npm run test exercice-4.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-4b
      id: exercice-4b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-4b
        setup-command: npm install
        command: npm run test exercice-4.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-4c
      id: exercice-4c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-4c
        setup-command: npm install
        command: npm run test exercice-4.test.js -- --subtest=c
        timeout: 10
        max-score: 1
    - name: exercice-5a
      id: exercice-5a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-5a
        setup-command: npm install
        command: npm run test exercice-5.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-5b
      id: exercice-5b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-5b
        setup-command: npm install
        command: npm run test exercice-5.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-5c
      id: exercice-5c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-5c
        setup-command: npm install
        command: npm run test exercice-5.test.js -- --subtest=c
        timeout: 10
        max-score: 1
    - name: exercice-5d
      id: exercice-5d
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-5d
        setup-command: npm install
        command: npm run test exercice-5.test.js -- --subtest=d
        timeout: 10
        max-score: 1
    - name: exercice-5e
      id: exercice-5e
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-5e
        setup-command: npm install
        command: npm run test exercice-5.test.js -- --subtest=e
        timeout: 10
        max-score: 1
    - name: exercice-6a
      id: exercice-6a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-6a
        setup-command: npm install
        command: npm run test exercice-6.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-6b
      id: exercice-6b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-6b
        setup-command: npm install
        command: npm run test exercice-6.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-6c
      id: exercice-6c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-6c
        setup-command: npm install
        command: npm run test exercice-6.test.js -- --subtest=c
        timeout: 10
        max-score: 1
    - name: exercice-6d
      id: exercice-6d
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-6d
        setup-command: npm install
        command: npm run test exercice-6.test.js -- --subtest=d
        timeout: 10
        max-score: 1
    - name: exercice-7a
      id: exercice-7a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-7a
        setup-command: npm install
        command: npm run test exercice-7.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-7b
      id: exercice-7b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-7b
        setup-command: npm install
        command: npm run test exercice-7.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-8a
      id: exercice-8a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-8a
        setup-command: npm install
        command: npm run test exercice-8.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-8b
      id: exercice-8b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-8b
        setup-command: npm install
        command: npm run test exercice-8.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-8c
      id: exercice-8c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-8c
        setup-command: npm install
        command: npm run test exercice-8.test.js -- --subtest=c
        timeout: 10
        max-score: 1
    - name: exercice-8d
      id: exercice-8d
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-8d
        setup-command: npm install
        command: npm run test exercice-8.test.js -- --subtest=d
        timeout: 10
        max-score: 1
    - name: exercice-9a
      id: exercice-9a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-9a
        setup-command: npm install
        command: npm run test exercice-9.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-9b
      id: exercice-9b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-9b
        setup-command: npm install
        command: npm run test exercice-9.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: exercice-9c
      id: exercice-9c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-9c
        setup-command: npm install
        command: npm run test exercice-9.test.js -- --subtest=c
        timeout: 10
        max-score: 1
    - name: exercice-9d
      id: exercice-9d
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-9d
        setup-command: npm install
        command: npm run test exercice-9.test.js -- --subtest=d
        timeout: 10
        max-score: 1
    - name: exercice-10a
      id: exercice-10a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-10a
        setup-command: npm install
        command: npm run test exercice-10.test.js -- --subtest=a
        timeout: 10
        max-score: 1
    - name: exercice-10b
      id: exercice-10b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: exercice-10b
        setup-command: npm install
        command: npm run test exercice-10.test.js -- --subtest=b
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXERCICE-1A_RESULTS: "${{steps.exercice-1a.outputs.result}}"
        EXERCICE-1B_RESULTS: "${{steps.exercice-1b.outputs.result}}"
        EXERCICE-2A_RESULTS: "${{steps.exercice-2a.outputs.result}}"
        EXERCICE-2B_RESULTS: "${{steps.exercice-2b.outputs.result}}"
        EXERCICE-2C_RESULTS: "${{steps.exercice-2c.outputs.result}}"
        EXERCICE-2D_RESULTS: "${{steps.exercice-2d.outputs.result}}"
        EXERCICE-3A_RESULTS: "${{steps.exercice-3a.outputs.result}}"
        EXERCICE-3B_RESULTS: "${{steps.exercice-3b.outputs.result}}"
        EXERCICE-3C_RESULTS: "${{steps.exercice-3c.outputs.result}}"
        EXERCICE-3D_RESULTS: "${{steps.exercice-3d.outputs.result}}"
        EXERCICE-3E_RESULTS: "${{steps.exercice-3e.outputs.result}}"
        EXERCICE-4A_RESULTS: "${{steps.exercice-4a.outputs.result}}"
        EXERCICE-4B_RESULTS: "${{steps.exercice-4b.outputs.result}}"
        EXERCICE-4C_RESULTS: "${{steps.exercice-4c.outputs.result}}"
        EXERCICE-5A_RESULTS: "${{steps.exercice-5a.outputs.result}}"
        EXERCICE-5B_RESULTS: "${{steps.exercice-5b.outputs.result}}"
        EXERCICE-5C_RESULTS: "${{steps.exercice-5c.outputs.result}}"
        EXERCICE-5D_RESULTS: "${{steps.exercice-5d.outputs.result}}"
        EXERCICE-5E_RESULTS: "${{steps.exercice-5e.outputs.result}}"
        EXERCICE-6A_RESULTS: "${{steps.exercice-6a.outputs.result}}"
        EXERCICE-6B_RESULTS: "${{steps.exercice-6b.outputs.result}}"
        EXERCICE-6C_RESULTS: "${{steps.exercice-6c.outputs.result}}"
        EXERCICE-6D_RESULTS: "${{steps.exercice-6d.outputs.result}}"
        EXERCICE-7A_RESULTS: "${{steps.exercice-7a.outputs.result}}"
        EXERCICE-7B_RESULTS: "${{steps.exercice-7b.outputs.result}}"
        EXERCICE-8A_RESULTS: "${{steps.exercice-8a.outputs.result}}"
        EXERCICE-8B_RESULTS: "${{steps.exercice-8b.outputs.result}}"
        EXERCICE-8C_RESULTS: "${{steps.exercice-8c.outputs.result}}"
        EXERCICE-8D_RESULTS: "${{steps.exercice-8d.outputs.result}}"
        EXERCICE-9A_RESULTS: "${{steps.exercice-9a.outputs.result}}"
        EXERCICE-9B_RESULTS: "${{steps.exercice-9b.outputs.result}}"
        EXERCICE-9C_RESULTS: "${{steps.exercice-9c.outputs.result}}"
        EXERCICE-9D_RESULTS: "${{steps.exercice-9d.outputs.result}}"
        EXERCICE-10A_RESULTS: "${{steps.exercice-10a.outputs.result}}"
        EXERCICE-10B_RESULTS: "${{steps.exercice-10b.outputs.result}}"
      with:
        runners: exercice-1a,exercice-1b,exercice-2a,exercice-2b,exercice-2c,exercice-2d,exercice-3a,exercice-3b,exercice-3c,exercice-3d,exercice-3e,exercice-4a,exercice-4b,exercice-4c,exercice-5a,exercice-5b,exercice-5c,exercice-5d,exercice-5e,exercice-6a,exercice-6b,exercice-6c,exercice-6d,exercice-7a,exercice-7b,exercice-8a,exercice-8b,exercice-8c,exercice-8d,exercice-9a,exercice-9b,exercice-9c,exercice-9d,exercice-10a,exercice-10b

    - name: Write feedback file
      id: write_feedback
      run: |
        cat > feedback.md <<'EOF'
        Autograding feedback
        Repository: ${{ github.repository }}
        Commit: ${{ github.sha }}
        Actor: ${{ github.actor }}
        
        Results:
        exercice-1a: ${{ steps.exercice-1a.outputs.result }}
        exercice-1b: ${{ steps.exercice-1b.outputs.result }}
        exercice-2a: ${{ steps.exercice-2a.outputs.result }}
        exercice-2b: ${{ steps.exercice-2b.outputs.result }}
        exercice-2c: ${{ steps.exercice-2c.outputs.result }}
        exercice-2d: ${{ steps.exercice-2d.outputs.result }}
        exercice-3a: ${{ steps.exercice-3a.outputs.result }}
        exercice-3b: ${{ steps.exercice-3b.outputs.result }}
        exercice-3c: ${{ steps.exercice-3c.outputs.result }}
        exercice-3d: ${{ steps.exercice-3d.outputs.result }}
        exercice-3e: ${{ steps.exercice-3e.outputs.result }}
        exercice-4a: ${{ steps.exercice-4a.outputs.result }}
        exercice-4b: ${{ steps.exercice-4b.outputs.result }}
        exercice-4c: ${{ steps.exercice-4c.outputs.result }}
        exercice-5a: ${{ steps.exercice-5a.outputs.result }}
        exercice-5b: ${{ steps.exercice-5b.outputs.result }}
        exercice-5c: ${{ steps.exercice-5c.outputs.result }}
        exercice-5d: ${{ steps.exercice-5d.outputs.result }}
        exercice-5e: ${{ steps.exercice-5e.outputs.result }}
        exercice-6a: ${{ steps.exercice-6a.outputs.result }}
        exercice-6b: ${{ steps.exercice-6b.outputs.result }}
        exercice-6c: ${{ steps.exercice-6c.outputs.result }}
        exercice-6d: ${{ steps.exercice-6d.outputs.result }}
        exercice-7a: ${{ steps.exercice-7a.outputs.result }}
        exercice-7b: ${{ steps.exercice-7b.outputs.result }}
        exercice-8a: ${{ steps.exercice-8a.outputs.result }}
        exercice-8b: ${{ steps.exercice-8b.outputs.result }}
        exercice-8c: ${{ steps.exercice-8c.outputs.result }}
        exercice-8d: ${{ steps.exercice-8d.outputs.result }}
        exercice-9a: ${{ steps.exercice-9a.outputs.result }}
        exercice-9b: ${{ steps.exercice-9b.outputs.result }}
        exercice-9c: ${{ steps.exercice-9c.outputs.result }}
        exercice-9d: ${{ steps.exercice-9d.outputs.result }}
        exercice-10a: ${{ steps.exercice-10a.outputs.result }}
        exercice-10b: ${{ steps.exercice-10b.outputs.result }}
        EOF

    - name: Commit and push feedback
      if: github.event_name == 'push' && github.actor != 'github-actions[bot]' && github.actor != 'github-classroom[bot]'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add feedback.md
        git commit -m "Add autograding feedback for ${{ github.sha }}" || echo "no changes to commit"
        git push origin HEAD:${{ github.ref_name }}
